<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>E-way Bill</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="bg-white">
<div class="p-5 ">
    <div class="text-end text-xs text-gray-500 p-0.5">Original Copy</div>
        <div class="w-full ">
        <div class="w-full inline-flex items-center justify-center bg-gray-100 text-black text-sm font-semibold p-1">
            <span class="">e-Way Bill</span>
        </div>
        <div class="w-full text-xs  tracking-wider flex items-center justify-between py-2 px-0.5">
            <div><span>Doc No:</span> <span class="font-semibold">Tax Invoice - 43</span></div>
            <div><span>Date:</span> <span class="font-semibold">{{date('y-m-d')}}</span></div>
        </div>
    </div>
    <div class="w-full inline-flex items-center justify-start bg-gray-100 text-black text-sm font-semibold p-1">
        <span class="">1. e-way Bill Details</span>
    </div>
    <div class="w-full flex">
        <div class="w-[80%] flex-col flex">
            <div class=" flex justify-between h-[160px]">
                <div
                    class="w-1/2 text-xs flex-col flex space-y-1 justify-evenly px-1 border-r border-gray-300">
                    <div class="inline-flex  "><span class="w-2/5">e-Way Bill No</span><span class="w-1/5">:</span><span
                            class="font-semibold w-2/5">5432121234565678</span></div>
                    <div class="inline-flex  "><span class="w-2/5">Generated By</span><span class="w-1/5">:</span><span
                            class="font-semibold w-2/5">33AEYFS0879K1Z5</span></div>
                    <div class="inline-flex "><span class="w-2/5">Supply By</span><span class="w-1/5">:</span><span
                            class="font-semibold w-2/5">Outward-Supply</span></div>
                    <div class="inline-flex "><span class="w-2/5">Mode</span><span class="w-1/5">:</span><span
                            class="font-semibold w-2/5">1 - Road</span>
                    </div>
                </div>
                <div class="w-1/2 text-xs flex-col flex space-y-1 justify-evenly px-1">
                    <div class="inline-flex "><span class="w-2/5">Approx Distance</span><span
                            class="w-1/5">:</span><span
                            class="font-semibold w-2/5">6 KM</span></div>
                    <div class="inline-flex "><span class="w-2/5">Transaction Type</span><span
                            class="w-1/5">:</span><span
                            class="font-semibold w-2/5">Regular</span></div>
                    <div class="inline-flex "><span class="w-2/5"> Generated Date</span><span
                            class="w-1/5">:</span><span
                            class="font-semibold w-2/5">{{date('y-m-d')}}</span></div>
                    <div class="inline-flex "><span class="w-2/5"> Valid Upto</span><span class="w-1/5">:</span><span
                            class="font-semibold w-2/5">{{date('y-m-d')}}</span></div>
                </div>
            </div>
        </div>
        <div class="w-[20%] h-[160px] border-l border-gray-300 flex items-center justify-center">
            @if($irn)
                <img class="w-[145px] h-auto rounded-sm"
                     src="{{\App\Helper\qrcoder::generate($irn->signed_qrcode,22)}}"
                     alt="{{$irn->signed_qrcode}}">
            @endif
        </div>
    </div>
    <div class="w-full inline-flex items-center justify-start bg-gray-100 text-black text-sm font-semibold p-1">
        <span class="">1. Address Details</span>
    </div>
    <div class="flex justify-between text-xs p-1 py-2">
        <div class="flex-col w-1/2 space-y-2">
            <div class="">
                <div class="font-semibold">From</div>
                <div>SK INTERNATIONAL</div>
                <div>GSTIN : 33AEYFS0879K1Z5</div>
                <div>Tamil Nadu</div>
            </div>
            <div class="">
                <div class="font-semibold">Dispatch From</div>
                <div> Ground Floor, SF.No. 390/1,, Tkt Thottam, Pitchampalayam</div>
                <div>Pudur,, P.N. Road, Thottipalayam,, Tiruppur.</div>
                <div> TIRUPUR Tamil Nadu 641602</div>
            </div>

        </div>
        <div class="flex-col w-1/2 space-y-2">
            <div class="">
                <div class="font-semibold">To</div>
                <div>SATYANARAYANA GARMENTS</div>
                <div>GSTIN : 33AEZFS3018M1ZF</div>
                <div>Tamil Nadu</div>
            </div>
            <div class="">
                <div class="font-semibold">Ship From</div>
                <div>321, SWAMYNATHAPURAM 1 ST STREET,,</div>
                <div>SWAMYNATHAPURAM, Velampalayam,, Tiruppur</div>
                <div>TIRUPUR Tamil Nadu 641603</div>
            </div>
        </div>
    </div>

    <div class="w-full inline-flex items-center justify-start bg-gray-100 text-black text-sm font-semibold p-1">
        <span class="">3. Good Details</span>
    </div>
    <!-- Item Table -->
    <div>
        <table class="w-full border-b border-t border-gray-300">
            <thead class="font-semibold text-[10px] bg-gray-50">
            <tr class="py-2 border-b border-r border-gray-300 tracking-wider">
{{--                <th class="py-2 w-[3%] px-1 border-r border-l border-gray-300">S.No</th>--}}
                <th class="py-2 w-[12%] border-l border-r border-gray-300">HSN Code</th>
                <th class="py-2 border-r border-gray-300 text-start px-1">Product name & Desc</th>
                <th class="py-2 w-[10%] border-r border-gray-300">Qty</th>
                <th class="py-2 w-[12%] border-r border-gray-300">Taxable Amount</th>
{{--                <th class="py-2 w-[3%] border-r border-gray-300">%</th>--}}
                <th class="py-2 w-[12%] border-r border-gray-300">Tax Rate (C + S)</th>
{{--                <th class="py-2 w-[10%] border-r border-gray-300">Sub Total</th>--}}
            </tr>
            </thead>
            <tbody>
            @php
                $gstPercent = 0;
            @endphp
            @foreach($list as $index => $row)
                <tr class="text-xs border-r border-gray-300">
{{--                    <td class="py-2 text-center border-l border-r border-gray-300">{{$index+1}}</td>--}}
                    <td class="py-2 text-center border-l border-r border-gray-300">{{$row['hsncode']}}</td>
                    <td class="py-2 text-start px-0.5 border-r border-gray-300">
                        @if($row['description'])
                            {{$row['product_name'].' - '.$row['description']}}
                        @else
                            {{$row['product_name']}}
                        @endif
                    </td>
                    <td class="py-2 px-0.5 border-r border-gray-300 text-center">{{$row['qty']+0}}</td>
                    <td class="py-2 text-end px-0.5 border-r border-gray-300 font-semibold">{{number_format($row['qty']*$row['price'],2,'.','')}}</td>
                    <td class="py-2 text-center border-r border-gray-300 ">{{$row['gst_percent']/2*2}}&nbsp;+&nbsp;{{$row['gst_percent']/2*2}}</td>
{{--                    <td class="py-2 text-end px-0.5 border-r border-gray-300">{{number_format($row['gst_amount'],2,'.','')}}</td>--}}
{{--                    <td class="py-2 text-end px-0.5 border-r border-gray-300 ">{{number_format($row['sub_total'],2,'.','')}}</td>--}}
                </tr>
            @endforeach
            @for($i = 0; $i < 9 - $list->count(); $i++)
                <tr class="text-xs border-r border-gray-300">

                    <td class="py-2 text-center  border-l border-r border-gray-300">&nbsp;</td>
                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>
                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>
                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>
                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>
{{--                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>--}}
{{--                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>--}}
{{--                    <td class="py-2 text-center border-r border-gray-300">&nbsp;</td>--}}
                </tr>
            @endfor

{{--            <tr class="text-xs py-1 font-semibold border-t border-r border-l border-gray-300">--}}
{{--                <td colspan="1" class="py-1 px-4">E&OE</td>--}}
{{--                <td class="py-1 border-r border-gray-300 text-end px-4">Total</td>--}}
{{--                <td class="text-end px-0.5 py-1 border-r border-l border-gray-300">{{number_format($obj->total_taxable,2,'.','')}}</td>--}}
{{--                <td class="py-1"></td>--}}
{{--                <td class="text-end px-0.5 py-1 border-r border-l border-gray-300">{{number_format($obj->total_gst,2,'.','')}}</td>--}}
{{--                <td class="text-end px-0.5 py-1 border-r border-l border-gray-300">{{number_format($obj->grand_total-$obj->additional,2,'.','')}}</td>--}}
{{--            </tr>--}}
            </tbody>
        </table>
    </div>
    <div class="flex text-xs border-b border-gray-300">
        <div class="w-1/3 flex-col border-l border-r border-gray-300 px-0.5 py-1 space-y-1">
            <div class="w-full inline-flex justify-between"><span class="w-2/5 ">Tot. Taxable Amt</span><span
                    class="w-1/5">:</span><span
                    class="w-w-2/5 text-end font-bold">  {{number_format($obj->total_taxable,2,'.','')}}</span></div>
            @if($obj->sales_type=='CGST-SGST')
                <div class="w-full inline-flex justify-between"><span
                        class="w-2/5">CGST&nbsp;@&nbsp;{{$gstPercent}}%</span><span class="w-1/5">:</span><span
                        class="w-2/5 text-end font-bold">{{number_format($obj->total_gst/2,2,'.','')}}</span></div>
            @else
                <div class="w-full inline-flex justify-between"><span class="w-2/5">IGST</span><span
                        class="w-1/5">:</span><span
                        class="w-2/5 text-end font-bold">{{number_format($obj->total_gst,2,'.','')}}</span></div>
            @endif
        </div>
        <div class="w-1/3 flex-col border-r border-gray-300 px-0.5 py-1 space-y-1">
            @if($obj->additional!=0)
                <div class="w-full inline-flex justify-between"><span class="w-2/5">Other Amt</span><span
                        class="w-2/5">:</span><span
                        class="w-2/5 text-end font-bold"> {{ number_format($obj->additional,2,'.','') }}</span>
                </div>
            @else
                <div class="w-full inline-flex justify-between"><span class="w-2/5"></span><span
                        class="w-1/5"></span><span class="w-2/5 text-end font-semibold"></span></div>
            @endif
            @if($obj->sales_type=='CGST-SGST')
                <div class="w-full inline-flex justify-between"><span
                        class="Other Amt">SGST&nbsp;@&nbsp;{{$gstPercent}}%</span><span class="w-1/5">:</span><span
                        class="w-2/5 text-end font-bold">{{number_format($obj->total_gst/2,2,'.','')}}</span></div>
            @else
                <div class="w-full inline-flex justify-between"><span class="w-2/5">&nbsp</span><span class="w-1/5">&nbsp;</span><span
                        class="w-2/5 text-end font-bold">&nbsp;</span></div>
            @endif
        </div>
        <div class="w-2/5 flex-col border-r border-gray-300 px-0.5 py-1 space-y-1">
            <div class="w-full inline-flex justify-between"><span class="w-2/5">Total Inv Amt</span><span
                    class="w-1/5">:</span><span
                    class="w-2/5 text-end font-bold"> {{number_format($obj->grand_total,2,'.','')}}</span></div>
            <div class="w-full inline-flex justify-between"><span class="w-2/5"></span><span class="w-1/5"></span><span
                    class="w-2/5 text-end"></span></div>
        </div>
    </div>
    <div class="w-full inline-flex items-center justify-start bg-gray-100 text-black text-sm font-semibold p-1">
        <span class="">4. Transportation Details</span>
    </div>
    <div class="w-full flex  text-xs ">
        <div class="w-1/2 flex-col p-1 space-y-1">
            <div class="flex justify-between">
                <span class="w-2/5">Transporter ID</span><span class="w-1/5">:</span><span class="w-2/5"></span>
            </div>
            <div class="flex justify-between">
                <span class="w-2/5">Name</span><span class="w-1/5">:</span><span class="w-2/5"></span>
            </div>
        </div>
        <div class="w-1/2 flex-col p-1 space-y-1">
            <div class="flex justify-between">
                <span class="w-2/5">Doc No</span><span class="w-1/5">:</span><span class="w-2/5"></span>
            </div>
            <div class="flex justify-between">
                <span class="w-2/5">Date</span><span class="w-1/5">:</span><span class="w-2/5"></span>

            </div>
        </div>
    </div>
    <div class="w-full inline-flex items-center justify-start bg-gray-100 text-black text-sm font-semibold p-1">
        <span class="">5. Vehicle Details</span>
    </div>
    <div class="w-full p-1 text-xs inline-flex items-center justify-between border-b border-gray-300 space-y-1">
        <div class="w-1/3 flex justify-between">
            <span class="w-2/5">Transporter ID</span><span class="w-1/5">:</span><span class="w-2/5"></span>
        </div>
        <div class="w-1/3 flex justify-between">
            <span class="w-2/5">From</span><span class="w-1/5">:</span><span class="w-2/5"></span>
        </div>
        <div class="w-1/3 flex justify-between">
            <span class="w-2/5">CEWB</span><span class="w-1/5">:</span><span class="w-2/5"></span>
        </div>
    </div>
</div>
</body>
</html>
